######################################################################
# Automatically generated by qmake (3.0) dom feb 25 17:34:15 2018
######################################################################

TEMPLATE = app
TARGET = Kalk
INCLUDEPATH += .

CONFIG += c++11


# Input
HEADERS += DataType.h datatypes/Matrix.h datatypes/SquareMatrix.h datatypes/SparseMatrix.h
SOURCES += DataType.cpp main.cpp datatypes/Matrix.cpp datatypes/SquareMatrix.cpp datatypes/SparseMatrix.cpp
